on:
  pull_request:
  push:
    branches:
      - master
      - 3.x

name: phpunit

jobs:
  phpunit:
    uses: spiral/gh-actions/.github/workflows/phpunit.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.1', '8.2']
      stability: >-
        ['prefer-lowest', 'prefer-stable']
